Feature/exist nickname - 중복 닉네임 확인
f-lab-edu/dogspot-auth-server pull request #14
Opened 2024-06-08 08:55 UTC by wngh4628

닉네임 중복 확인하는 기능입니다.
#13

2024-06-10 11:15 UTC, f-lab-darwin requested changes
전체적으로 살펴봤는데, 우선 별도로 코멘트 한것부터 보시고, 필요한 것은 별도 이슈를 통해 진행하도록 하시죠.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/app.module.ts
> +import { UserModule } from './domains/user/user.module';
import를 할 경우 framework, library에서 가져오는 것들을 유사한 것끼리 먼저 가져오고, 
user code는 한줄 띄우고 유사한 것끼리 묶어서 가져오는 식으로 분류가 되도록 하면 가독성이 좋습니다.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/app.module.ts
> +      envFilePath: process.env.NODE_ENV === 'dev' ? '.env.dev' : '.env.prod',
.env.dev와 .env.prod 파일이 없는것 같네요.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/core/decorators/auth-user.decorator.ts
> +    console.log('request: ', request.user);
decorator에 log를 남기는 것은 개발시 테스트 용으로 사용하는 것은 괜찮으나, 상용에서는 개발자의 의도와 상관없이 로그를 남기게 되므로 log를 남기지 않도록 하시죠.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/core/decorators/typeorm-ex.decorator.ts
> + */
해당 decoroator의 목적과 용도를 구체적으로 코멘트로 설명해 주시면 어떤 목적으로 어떤 상황에서 해당 decorator를 사용할 수 있을지 확인하는데 도움이 될 것 같아요.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/core/http/http-error-objects.ts
> +    message: '로그인이 필요합니다.',
message는 i18n 처리가 필요한데, 추후 별도로 다루어 보시죠.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/core/http/response-json.ts
> +  };
object가 undefined인 경우와 아닌 경우 차이가 없는데, 구분한 이유가 있을까요?

2024-06-10 11:15 UTC, f-lab-darwin commented on src/core/swagger/swagger-config.ts
> +  SwaggerModule.setup('api-docs', app, swaggerDocument, swaggerOptions);
swaggerOptions가 뒤에 있는데, 실행이 제대로 되는지 확인이 필요하네요.
변수 선언 순서는 잘 확인해 보시기 바랍니다.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/domains/auth/auth.controller.ts
> +
다른 곳에서도 언급했듯이, import 종류별로 그룹핑과 순서를 Convention을 가지고 사용하도록 하시죠.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/domains/auth/auth.controller.ts
> +  @Post()
login을 URL Path에 넣어서 명시적으로 하는 것을 추천해요.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/domains/auth/jwt/jwt.strategy.ts
> +    // if (!userInfo) {
개발할때 테스트용으로 사용했던 코드를 코멘트로 남기지 말고, 없애는 방향으로 하시죠. 보통 이렇게 남겨진 코드는 추후 다른 사람이 손대지 못하기도 하고, 남긴 본인도 시간이 지나면 사용하지 않게 됩니다.

2024-06-10 11:15 UTC, f-lab-darwin commented on src/main.ts
> +import { logger } from './utils/logger';
logging은 추후 log 수집을 위해서도 통일성 있게 사용해야 합니다. 전체적으로 console.log와 nest의 log와 winston을 섞어서 사용하고 있어서 관리의 어려움이 있어 보이네요.
추후 따로 이슈를 잡고 진행해 보시죠.

2024-06-11 11:27 UTC, wngh4628 commented on src/app.module.ts
> +      envFilePath: process.env.NODE_ENV === 'dev' ? '.env.dev' : '.env.prod',
.env 파일은 public이라 gitignore에 추가해서 올리지 않았습니다.

2024-06-11 11:36 UTC, wngh4628 commented on src/core/decorators/typeorm-ex.decorator.ts
> + */
저도 해당 데코레이터가 무슨 용도인지 잘 모르겠습니다.

2024-06-11 11:48 UTC, wngh4628 commented on src/main.ts
> +import { logger } from './utils/logger';
네 알겠습니다.

2024-06-11 11:48 UTC, wngh4628 commented on src/domains/auth/jwt/jwt.strategy.ts
> +    // if (!userInfo) {
수정 했습니다.

2024-06-11 11:49 UTC, wngh4628 commented on src/domains/auth/auth.controller.ts
> +  @Post()
엔드 포인트를 'login'으로 변경했습니다

2024-06-11 11:49 UTC, wngh4628 commented on src/domains/auth/auth.controller.ts
> +
수정 했습니다.

2024-06-11 11:49 UTC, wngh4628 commented on src/core/swagger/swagger-config.ts
> +  SwaggerModule.setup('api-docs', app, swaggerDocument, swaggerOptions);
작동하는거 확인했습니다!

2024-06-11 11:49 UTC, wngh4628 commented on src/core/http/http-error-objects.ts
> +    message: '로그인이 필요합니다.',
네 알겠습니다

2024-06-11 11:50 UTC, wngh4628 commented on src/app.module.ts
> +import { UserModule } from './domains/user/user.module';
수정했습니다.

2024-06-11 12:07 UTC, f-lab-darwin approved these changes
추가로 수정이 필요한 부분이 있으면 따로 수정하시고, 본 건은 Approve로 하고 진행하시죠.
main branch로 merge가 되도록 하면 됩니다.
추후부터는 jenkins나 github action을 통해서 자동으로 build가 될 수 있도록 구성해 보시기 바랍니다.

2024-06-27 02:27 UTC, merged